config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get 'tasks', to: 'tasks#index'
    get 'task/new', to: 'tasks#new'
    post 'tasks', to: 'tasks#create'
    get 'task/:id', to: 'tasks#show', as: :task
    get 'task/:id/edit', to: 'tasks#edit', as: :task_edit
    patch 'task/:id', to: 'tasks#update'
    delete 'task/:id', to: 'tasks#destroy'
end

  # get    "restaurants",          to: "restaurants#index"

  # get    "restaurants/new",      to: "restaurants#new"
  # post   "restaurants",          to: "restaurants#create"

  # # NB: The `show` route needs to be *after* `new` route.
  # get    "restaurants/:id",      to: "restaurants#show"

  # get    "restaurants/:id/edit", to: "restaurants#edit"
  # patch  "restaurants/:id",      to: "restaurants#update"

  # delete "restaurants/:id",      to: "restaurants#destroy"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to task_path(task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to task_path(task)
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1><%=@task.title%></h1>

<%=form_for @task do |f|%>
<%=f.text_field :title%>
<%=f.text_field :details%>
<%=f.check_box :completed%>
<%=f.submit%>
<%end%>

<div class="back-btn"><%= link_to "back to task", task_path(@task)%></div>

app/views/tasks/index.html.erb
<h1>Your Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <%completed = task.completed == true ? "🔘" : "⚪️" %>
    <div class="list-task"><li class="task_item"><%=completed%><span class="flex-grow"> <%=link_to "#{task.title}", task_path(task)%> </span><%= link_to "❌", task_path(task), method: :delete, data: { confirm: "Are you sure?" } %></li></div>

  <% end %>
</ul>

<div class="new-btn"><%=link_to "Add a Task", task_new_path%></div>

app/views/tasks/new.html.erb
<h1>Add a new Task</h1>

<%=form_for @task do |f|%>
<%=f.text_field :title%>
<%=f.text_field :details%>
<%=f.submit%>
<%end%>

app/views/tasks/show.html.erb
<h1><%=@task.title %></h1>
<%completed = @task.completed == true ? "☑ This Task has been completed" : "☒ This Task has not been completed" %>
<p class="single-details"><%=@task.details%></p>
<p class="single-completed"><%=completed%></p>
<div class="flex-btn">
  <div class="back-btn"><%= link_to "edit task", task_edit_path(@task)%></div>
  <div class="back-btn"><%= link_to "back to all tasks", tasks_path%></div>
</div>